[package]
name = "visusta-core"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.8", features = ["rayon", "serde"] }
libm = "0.2.15"
log = "0.4.29"
rayon = "1.11.0"
wgpu = "27.0.1"

[dev-dependencies]
anyhow = "1.0.100"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
